# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fdfbfff3e77968e8d1d1882403a163cb13383d0897920771e00cacf09f2711af57a081f1df6f70a232fd7ac8646fb6a99419fceac88af1508d68d32b6971993

test:
  secret_key_base: e8108c08640948fd297b607300387d4532296e134bcf9c0c79ebbe11c328deddd9d4b56fb67886f029eb4068b4268c85338848cb81f5858d414eefb930ab4a71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
